### ISSUE TITLE
Feature request: Add global align functions

### ISSUE THREAD

**Issue by luojing1211** [quatrope/astroalign#38]
I am currently align some images with a lot of noise.  I can find sources around a small part of the image and align them. However, it requires a different transformation for the global image.  Is there any feature that can convert the transformation class to another coordinate?

**Comment by martinberoiz** [comment]
Hi JL! That seems like a neat idea, do you have a concrete example of how it would work?

**Comment by luojing1211** [comment]
I would like to know, when applying the transformation. where is the
rotation origin?
-Jing

**Comment by martinberoiz** [comment]
I may be wrong on this one, but here's my take.

Since the whole matrix is a rotation + translation, where the origin is, depends on wether you think of it as a TR or RT transformation.
If you think of it as a combination of a rotation and then a translation (TR) then the origin is at pixel (0, 0) of the original image. 
If you think of it as a translation and then rotation (RT), then the origin of the rotation is at (tx, ty) given by the first translation (tx, ty measured on the original image).

In both cases the matrix will be the same in terms of the numbers in it, but the order in which you apply those two may change what you call the origin of rotation.

**Comment by luojing1211** [comment]
In the function apply_align(), how is it applied? Pulse in the transform
class, where is the rotation and translation information stored.
-Jing

**Comment by luojing1211** [comment]
Hi Martin. 
I think I figure out a way. It will have to be in the find_transformation(). After we find the sources, we can transform the source position to the original image position, and than get the transformation matrix. Is it possible in the find_transformation() function?

**Comment by martinberoiz** [comment]
Yes, I was thinking that that would be the way to go.

This is how I would do it.

If you only know the (x, y) positions of sources relative to a smaller section of the image, you run find_transform to find a correspondence of (x, y) pairs in that section and the second image.

    __, (sources_section, sources_dest) = aa.find_transform(xy_section, xy_second_image)

The transformation returned by `find_transform` at this point is not useful.
So we transform back `sources_section` to the x, y they'd had in the full image

    sources_first_image = sources_section + (x_offset, y_offset)  # this is just pseudocode

Then, use `estimate transform` from `scikit_image` (it's in aa as well) to estimate the transform between the sources in the full images.

    transf = aa.estimate_transform(sources_first_image, sources_second_image)

and then use that transform to apply to the whole image.

    img_aligned = aa.apply_transform(first_image, second_image, transf)

The code above may not be 100% correct, I didn't test it.
I honestly don't know how frequent would this situation be to add as a feature, or what API to use.
